print ("enter three number")
a=input()
b=input()
c=input()
print("first no :",a)
print("second no :",b)
print("third no :",c)
print("addition of a b c :",a+b+c)
#print("multiplication of a b c :",a*b*c)